name: Python script validation

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  validate:
    uses: amaldonadomat/centralized-workflows-example/.github/workflows/python-validation.yml@main
    with:
      python-version: "3.11"
      script-path: "python-scripts/factorial.py"
      script-input: "10"